---
- name: Copy the sample template of server configuration
  template:
  args:
    src: server.conf.j2
    dest: /{{ base_directory }}/server.conf

- name: Copy the sample template of client configuration
  template:
  args:
    src: client.conf.j2
    dest: /{{ base_directory }}/client.conf

- name: Indicating PORT & PROTOCOL in server.conf
  lineinfile:
    dest: /{{ base_directory }}/server.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: 'port 1194', line: 'port {{ PORT }}' }
  - { regexp: 'proto udp', line: 'proto {{ PROTOCOL }}' }

- name: Getting public IP for client.conf
  ipify_facts:

- name: Indicating PORT & PROTOCOL in client.conf
  lineinfile:
    dest: /{{ base_directory }}/client.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: 'proto udp', line: 'proto {{ PROTOCOL }}' }
  - { regexp: 'remote my-server-1 1194', line: 'remote {{ ipify_public_ip }} {{ PORT }}' }
  notify:
    - daemon_reload
    - starting_openvpn
...