---
- name: Downloading easy rsa
  get_url:
    url: "{{ easy_rsa_url }}"
    dest: /tmp/
    validate_certs: False

- name: Unarchiving easy-rsa
  unarchive:
    src: /tmp/{{ easy_rsa_pkg }}.tgz
    dest: /tmp
    creates: /tmp/{{ easy_rsa_pkg }}
    remote_src: true

- name: Copying rsa files to the working directory
  command: cp -r /tmp/{{ easy_rsa_pkg }} /{{ base_directory }}/easy-rsa
  args:
    creates: /{{ base_directory }}/easy-rsa
...