---
- name: Installing openvpn package and updating cache for ubuntu & Debian
  apt:
    pkg: openvpn
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu" or ansible_distribution=="Debian"

- name: Install EPEL repository
  yum:
    name: "{{ epel_repo }}"
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Install EPEL for for Redhat & Centos
  package:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Install openvpn for Redhat & Centos
  yum:
    name: openvpn
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: yes
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Changing the ownership of openvpn client for Redhat & Centos
  file:
    path: /etc/openvpn/client
    owner: root
    group: root
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Changing the ownership of openvpn server for Redhat & Centos
  file:
    path: /etc/openvpn/server
    owner: root
    group: root
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"
...